"""Lightweight keyword-based topic detection for the dev chat UI's cartoon
illustrations -- e.g. an addition question gets a scene of pennies being
counted, a fractions question gets a sliced pizza.

Deliberately separate from the safety guardrail pipeline
(backend/app/guardrails/) even though the pattern looks similar (keyword
matching against a message): this classifier has zero safety weight. A
missed or wrong topic match just means no illustration renders, or the
wrong one does -- never a safety-relevant outcome. Keep it that way; if this
ever needs to influence what content is allowed, it belongs in the
guardrail pipeline instead, not bolted onto this module.

Same "no third-party API" rule as everywhere else in this app: illustrations
are pre-built SVG scenes composed client-side
(backend/app/static/index.html), not generated by an image model. This
module only decides *which* scene and what numbers to parameterize it with.
"""
from __future__ import annotations

import re

# Order matters: math topics are checked before general-knowledge topics so
# a message like "add up how many planets there are" resolves to ADDITION
# (the more specific, illustration-relevant hook) rather than SCIENCE.
_TOPIC_KEYWORDS: list[tuple[str, list[str]]] = [
    ("addition", ["plus", "add ", "adding", "addition", " sum ", "altogether", "combine", "in total", "how many in all"]),
    ("subtraction", ["minus", "subtract", "subtraction", "take away", "how many are left", "difference between"]),
    ("multiplication", ["times", "multiply", "multiplication", "groups of", "product of"]),
    # "how many groups of" deliberately excluded -- it's a substring collision
    # with multiplication's "groups of" keyword, which is checked first in
    # this list, so it would never actually reach this row.
    ("division", ["divide", "division", "divided by", "divided into", "split evenly",
                  "share equally"]),
    ("fractions", ["fraction", "numerator", "denominator", "half of", "quarter of", "slices of"]),
    # "square" deliberately excluded as a bare keyword -- it's overloaded
    # with math operations ("square root", "3 squared", "what is an
    # exponent... squared"), which real-world testing showed misfiring into
    # this (irrelevant) illustration topic instead of the math one. Specific
    # phrases catch the actual "square the shape" question without that
    # collision.
    ("shapes", ["shape", "circle", "triangle", "rectangle", "geometry", "sides does", "angle",
                "square shape", "draw a square", "square have", "corners does a square"]),
    ("science", ["planet", "space", "solar system", "moon", "star", "sun", "atom", "gravity", "volcano", "ocean current"]),
    ("animals", ["animal", " dog", " cat ", "whale", "lion", "elephant", " bird", " fish", "puppy", "kitten"]),
    ("reading", ["spell", "spelling", "vocabulary", "what does the word", "book report", "poem", "rhyme"]),
    ("columbus", ["christopher columbus", "columbus come", "columbus sail", "columbus discover", "columbus get to america"]),
]

_NUMBER_RE = re.compile(r"\d+")

_DEFAULT_NUMBERS = {
    "addition": (3, 2),
    "subtraction": (5, 2),
    "multiplication": (3, 4),
    "division": (12, 4),
    "fractions": (1, 4),
}


def classify(message: str) -> str | None:
    text = message.lower()
    for topic, keywords in _TOPIC_KEYWORDS:
        if any(kw in text for kw in keywords):
            return topic
    return None


def extract_numbers(message: str, topic: str) -> list[int]:
    """Pulls up to two small numbers out of the message to parameterize a
    math illustration (e.g. "3 + 5" -> [3, 5]). Falls back to a fixed,
    pleasant default per topic if none are found or they're too large to
    render as individual countable objects (capped at 12).
    """
    found = [int(n) for n in _NUMBER_RE.findall(message)]
    found = [n for n in found if 0 < n <= 12]

    if len(found) >= 2:
        return found[:2]
    if topic in _DEFAULT_NUMBERS:
        return list(_DEFAULT_NUMBERS[topic])
    return []
